#!/usr/bin/env node
// 運営機能・タグ登録フローの結合テスト（ローカル、seed-demo 後）
import { readFileSync } from "node:fs";
import { client } from "./lib.mjs";

const base = process.argv[2] ?? "http://127.0.0.1:5173";
const setupToken = process.argv[3] ?? "dev-setup-token";
const ids = JSON.parse(readFileSync("seed/demo-ids.json", "utf8"));
let pass = 0, failed = 0;
const check = (n, ok, x) => (ok ? (pass++, console.log(`  ✓ ${n}`)) : (failed++, console.log(`  ✗ ${n}`, x === undefined ? "" : JSON.stringify(x))));
const ops = client(base);

console.log("運営: 初期化・認証");
let r = await ops.req("GET", "/api/ops/tenants");
check("未ログインは401", r.status === 401);
r = await ops.req("POST", "/api/ops/bootstrap", { setupToken: "wrong", name: "運営", email: "ops@straid.example", password: "ops-password-123" });
check("誤ったセットアップトークンは403", r.status === 403);
r = await ops.req("POST", "/api/ops/bootstrap", { setupToken, name: "武林", email: "ops@straid.example", password: "ops-password-123" });
if (r.status === 409) await ops.post("/api/ops/login", { email: "ops@straid.example", password: "ops-password-123" });
else check("オーナー作成", r.status === 200, r.data);
check("2回目の初期化は409", (await client(base).req("POST", "/api/ops/bootstrap", { setupToken, name: "x", email: "x@x.jp", password: "0123456789" })).status === 409);
const me = await ops.get("/api/ops/me");
check("運営 me", me.role === "owner", me);
const tenantCookieOnly = client(base);
await tenantCookieOnly.post("/api/auth/login", ids.admin);
check("テナント管理者は運営APIに入れない", (await tenantCookieOnly.req("GET", "/api/ops/tenants")).status === 401);

console.log("テナント作成");
const code = "T" + Date.now().toString(36).toUpperCase().slice(-6);
const created = await ops.post("/api/ops/tenants", { name: "テスト株式会社", code, plan: "trial", status: "trial", trialDays: 14, siteName: "第一倉庫", admin: { name: "山田", email: `${code.toLowerCase()}@example.com` } });
check("テナント作成（初期パスワード発行）", !!created.initialPassword, created);
const t = client(base);
await t.post("/api/auth/login", { email: created.adminEmail, password: created.initialPassword });
const tme = await t.get("/api/auth/me");
check("新テナント管理者ログイン", tme.orgStatus === "trial" && tme.planName === "トライアル", tme);
const list = await ops.get("/api/ops/tenants");
check("テナント一覧", list.some((x) => x.id === created.id));

console.log("タグ在庫 → 出荷 → 現地登録");
const batch = "E2E-" + Date.now();
const hex = (n) => [...crypto.getRandomValues(new Uint8Array(n))].map((b) => b.toString(16).padStart(2, "0")).join("").toUpperCase();
const TAG_UID = "04" + hex(6);
const BADGE_UID = hex(4);
const gen = await ops.post("/api/ops/stock/generate", { count: 5, itemType: "location_tag", chip: "ntag213", batch });
check("在庫発行", gen.created === 5, gen);
const genBadge = await ops.post("/api/ops/stock/generate", { count: 2, itemType: "badge", chip: "mifare", batch: batch + "-B" });
const csv = await ops.req("GET", `/api/ops/stock/export.csv?batch=${batch}`);
check("エンコード用CSV", csv.status === 200 && csv.data.includes(`/t/${gen.ids[0]}`), csv.status);
check("ラベル印刷", (await ops.req("GET", `/api/ops/stock/labels?batch=${batch}`)).status === 200);
const alloc = await ops.post("/api/ops/stock/allocate", { orgId: created.id, batch, count: 4, shipmentNote: "佐川 123" });
check("テナントへ4枚出荷", alloc.allocated === 4, alloc);
const notShipped = gen.ids.find((x) => !alloc.ids.includes(x));
const imp = await ops.post("/api/ops/stock/import-uids", { rows: [{ id: genBadge.ids[0], uid: BADGE_UID }, { id: alloc.ids[0], uid: TAG_UID }] });
check("UID取込", imp.updated === 2, imp);
await ops.post("/api/ops/stock/allocate", { orgId: created.id, ids: [genBadge.ids[0]] });
const stock = await t.get("/api/admin/tag-stock");
check("テナントで受領タグが見える", stock.filter((s) => s.status === "allocated").length === 5, stock.length);
r = await t.req("GET", `/api/tags/${alloc.ids[0]}`);
check("未登録タグのタッチ → tag_unregistered", r.status === 404 && r.data.code === "tag_unregistered", r.data);
r = await t.req("GET", `/api/tags/${notShipped}`);
check("他社（未出荷）タグは通常の404", r.status === 404 && r.data.code !== "tag_unregistered", r.data);
const { sites } = await t.get("/api/admin/sites");
r = await t.req("POST", "/api/admin/tags/register", { stockId: alloc.ids[0].slice(0, 5) + "-" + alloc.ids[0].slice(5).toLowerCase(), siteId: sites[0].id, kind: "checkpoint", label: "倉庫 入口", serial: TAG_UID });
check("登録コード（ハイフン・小文字可）で登録", r.status === 200 && r.data.id === alloc.ids[0], r.data);
r = await t.req("POST", "/api/admin/tags/register", { stockId: alloc.ids[3], siteId: sites[0].id, kind: "checkpoint", label: "x", serial: TAG_UID });
check("別タグのUIDでの登録は409", r.status === 409, r.data);
r = await t.req("POST", "/api/admin/tags/register", { stockId: alloc.ids[0], siteId: sites[0].id, kind: "checkpoint", label: "x" });
check("二重登録は409", r.status === 409, r.data);
const tapR = await t.req("POST", "/api/tap", { tagId: alloc.ids[0], clientEventId: crypto.randomUUID(), occurredAt: Date.now(), source: "pwa_webnfc", serial: TAG_UID });
check("登録したタグでタップ（UID照合=medium）", tapR.data.assurance === "medium", tapR.data);
await t.post("/api/admin/routes", { siteId: sites[0].id, name: "テスト巡回", tagIds: [alloc.ids[0]] });
r = await t.req("POST", `/api/admin/tags/${alloc.ids[0]}/replace`, { stockId: alloc.ids[1], reason: "破損" });
check("タグ交換", r.status === 200, r.data);
const routes = await t.get("/api/admin/routes");
check("交換で巡回ルートが新タグへ引継ぎ", routes[0].points[0].tagId === alloc.ids[1], routes[0].points);
const users = await t.get("/api/admin/users");
r = await t.req("PUT", `/api/admin/users/${users[0].id}/badge`, { stockId: genBadge.ids[0] });
check("社員証の割当", r.status === 200, r.data);
check("社員証UIDがユーザーに設定", (await t.get("/api/admin/users"))[0].badge_uid === BADGE_UID);

console.log("プラン上限・機能制御");
r = await t.req("GET", `/api/analytics/heatmap?siteId=${sites[0].id}`);
check("トライアルはヒートマップ不可", r.status === 403 && r.data.code === "plan_required", r.data);
r = await t.req("POST", "/api/admin/devices", { siteId: sites[0].id, kind: "ble_receiver", name: "x" });
check("トライアルはIoTデバイス不可", r.status === 403, r.data);
await ops.must("PATCH", `/api/ops/tenants/${created.id}`, { maxTagsOverride: 1 });
r = await t.req("POST", "/api/admin/tags/register", { stockId: alloc.ids[2], siteId: sites[0].id, kind: "checkpoint", label: "上限テスト" });
check("タグ上限の個別設定が効く", r.status === 403 && r.data.code === "limit_reached", r.data);
await ops.must("PATCH", `/api/ops/tenants/${created.id}`, { plan: "pro", status: "active", maxTagsOverride: null });
check("プラン変更でヒートマップ可", (await t.req("GET", `/api/analytics/heatmap?siteId=${sites[0].id}`)).status === 200);

console.log("契約停止・代理ログイン");
await ops.must("PATCH", `/api/ops/tenants/${created.id}`, { status: "suspended" });
r = await t.req("GET", "/api/auth/me");
check("停止中テナントは403", r.status === 403 && r.data.code === "contract_blocked", r.data);
check("停止中はログイン不可", (await client(base).req("POST", "/api/auth/login", { email: created.adminEmail, password: created.initialPassword })).status === 403);
const impC = client(base);
impC.clearCookie();
// 運営セッションを複製して代理ログイン
const opsCookie = ops.cookie();
r = await impC.req("POST", `/api/ops/tenants/${created.id}/impersonate`, { reason: "E2E サポート" }, { cookie: opsCookie });
check("代理ログイン", r.status === 200, r.data);
const impMe = await impC.req("GET", "/api/auth/me");
check("代理ログインは停止中でも閲覧可・フラグ付き", impMe.status === 200 && !!impMe.data.impersonatedBy, impMe.data);
const tAudit = await impC.get("/api/admin/audit");
check("テナント監査ログに代理ログインが残る", tAudit.some((a) => a.action === "support.impersonation"));
await ops.must("PATCH", `/api/ops/tenants/${created.id}`, { status: "active" });

console.log("パスワード変更でセッション失効");
const t2 = client(base);
await t2.post("/api/auth/login", { email: created.adminEmail, password: created.initialPassword });
await t.post("/api/auth/change-password", { current: created.initialPassword, next: "new-password-123" });
check("他端末のセッションは失効", (await t2.req("GET", "/api/auth/me")).status === 401);
check("変更した本人は継続", (await t.req("GET", "/api/auth/me")).status === 200);

console.log("請求");
const period = new Date(Date.now() + 9 * 3600e3).toISOString().slice(0, 7);
const g = await ops.post("/api/ops/invoices/generate", { period, orgIds: [created.id] });
check("請求書下書き作成", g.created === 1, g);
const invs = await ops.get(`/api/ops/invoices?period=${period}`);
const inv = invs.find((i) => i.org_id === created.id);
check("プロ基本料が計上", inv.subtotal >= 29800, inv);
check("下書きはテナントに見えない", (await t.get("/api/account/invoices")).length === 0);
await ops.must("PATCH", `/api/ops/invoices/${inv.id}`, { status: "issued" });
const tinv = await t.get("/api/account/invoices");
check("発行後テナントに表示", tinv.length === 1 && tinv[0].due_at > 0, tinv);
r = await t.req("GET", `/api/account/invoices/${inv.id}/print`);
check("請求書HTML", r.status === 200 && r.data.includes("請求書"), r.status);
await ops.must("PATCH", `/api/ops/invoices/${inv.id}`, { status: "paid" });
check("入金済み", (await t.get("/api/account/invoices"))[0].status === "paid");

console.log("お知らせ・サポート");
await ops.post("/api/ops/announcements", { title: "E2E メンテナンス", body: "本日22時より", level: "maintenance" });
await ops.post("/api/ops/announcements", { title: "個別連絡", body: "貴社のみ", orgId: created.id });
const ann = await t.get("/api/account/announcements");
check("全体＋個別のお知らせ", ann.some((a) => a.title === "E2E メンテナンス") && ann.some((a) => a.title === "個別連絡"), ann.map((a) => a.title));
const demo = client(base);
await demo.post("/api/auth/login", ids.admin);
check("個別お知らせは他社に出ない", !(await demo.get("/api/account/announcements")).some((a) => a.title === "個別連絡"));
const tk = await t.post("/api/account/tickets", { subject: "タグが反応しない", category: "tags", body: "入口のタグが読めません" });
const opsT = await ops.get("/api/ops/tickets");
check("運営に問い合わせが届く", opsT.some((x) => x.id === tk.id && x.status === "open"));
await ops.post(`/api/ops/tickets/${tk.id}/reply`, { body: "交換品を発送します" });
const th = await t.get(`/api/account/tickets/${tk.id}`);
check("回答がテナントに届く", th.ticket.status === "answered" && th.messages.length === 2, th.ticket);

console.log("運営ダッシュボード・設定・監査");
const dash = await ops.get("/api/ops/dashboard");
check("ダッシュボード", dash.tenants.total >= 2 && dash.mrr > 0, { tenants: dash.tenants, mrr: dash.mrr });
await ops.must("PUT", "/api/ops/settings", { invoice_registration_no: "T1234567890123", bank_info: "○○銀行 立川支店 普通 1234567" });
check("設定保存", (await ops.get("/api/ops/settings")).invoice_registration_no === "T1234567890123");
const staff = await ops.post("/api/ops/admins", { name: "スタッフ", email: `staff${Date.now()}@straid.example`, role: "staff" });
const st = client(base);
const sEmail = (await ops.get("/api/ops/admins")).find((a) => a.id === staff.id).email;
await st.post("/api/ops/login", { email: sEmail, password: staff.temporaryPassword });
check("スタッフは鍵付きCSV不可", (await st.req("GET", `/api/ops/stock/export.csv?batch=${batch}&keys=1`)).status === 403);
check("スタッフはプラン変更不可", (await st.req("PUT", "/api/ops/plans/pro", {})).status === 403);
const audit = await ops.get("/api/ops/audit");
check("運営監査ログ", ["tenant.create", "stock.allocate", "tenant.impersonate", "invoice.paid"].every((a) => audit.some((x) => x.action === a)));

console.log(`\n結果: ${pass} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
